# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- development
- test

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        repository: $(repository)
        dockerfile: '$(Build.SourcesDirectory)/containter/Dockerfile'
        tags: $(stage)
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: $(dockerHub)
    - task: Docker@2
      displayName: Push image
      inputs:
        containerRegistry: $(dockerHub)
        repository: $(repository)
        command: push
        tags: |
          $(stage)